/**
 * End-to-end compile against the real bundled toolchain.
 *
 * Excluded from `pnpm test` (see vitest.config.ts) because it needs a populated
 * `resources/` tree — run `pnpm toolchain:fetch` first — and a cloned
 * CommandStation-EX. Run it explicitly with:
 *
 *   pnpm vitest run tests/renderer/compile.integration.test.ts --exclude ''
 *
 * This is the test that proves the offline claim: `pioEnv()` points all HTTP at
 * a dead port, so if PlatformIO tries to download a platform, toolchain or
 * library, the build fails here rather than silently succeeding online.
 */
import { describe, it, expect, beforeAll, afterAll } from 'vitest'
import { spawn } from 'child_process'

import fs from 'fs/promises'
import os from 'os'
import path from 'path'

// Source repo cloned by the app — must exist before running this test.
const SOURCE_REPO = path.join(os.homedir(), 'dcc-rail-commander', 'repos', 'CommandStation-EX')

// Scratch dir mirrors what the GUI creates: _build/<board>-<hash>-<id>/CommandStation-EX
const SCRATCH_BASE = path.join(os.tmpdir(), 'dcc-rail-commander-test-build')
const REPO = path.join(SCRATCH_BASE, 'CommandStation-EX')

// Arduino Mega — fully supported and compiles reliably.
const FQBN = 'arduino:avr:mega:cpu=atmega2560'

// The bundled runtime, resolved the same way `pio-runtime.ts` does in dev.
const RESOURCES = path.resolve(__dirname, '../../resources')
const PYTHON = process.platform === 'win32'
    ? path.join(RESOURCES, 'python', 'python.exe')
    : path.join(RESOURCES, 'python', 'bin', 'python3')
const CORE_DIR = path.join(os.homedir(), 'dcc-rail-commander', 'platformio')

const MEGA_CONFIG_H = `\
// config.h - Generated by DCC-Rail-Commander (integration test) for Arduino Mega

#define IP_PORT 2560
#define SCROLLMODE 1
#define MOTOR_SHIELD_TYPE STANDARD_MOTOR_SHIELD
#define WIFI_HOSTNAME "dccex"
#define DISABLE_EEPROM
`

const PLATFORMIO_INI = `\
[platformio]
default_envs = mega2560
src_dir = .
include_dir = .
build_dir = .pio/build
libdeps_dir = .pio/libdeps

[env:mega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_flags = -Wall -Wextra
lib_extra_dirs = ${path.join(RESOURCES, 'pio-libs').replace(/\\/g, '/')}
monitor_speed = 115200
`

/** Source-file extensions the GUI copies (excludes .example / .template). */
const ALLOWED_EXTS = ['.ino', '.cpp', '.h']
const ALLOWED_SUBDIRS = ['src', 'libraries']

async function copySourceFiles(src: string, dest: string): Promise<void> {
    await fs.mkdir(dest, { recursive: true })
    const entries = await fs.readdir(src, { withFileTypes: true })
    for (const entry of entries) {
        const srcPath = path.join(src, entry.name)
        const destPath = path.join(dest, entry.name)
        if (entry.isDirectory() && ALLOWED_SUBDIRS.includes(entry.name)) {
            await copySourceFiles(srcPath, destPath)
        } else if (entry.isFile()) {
            const name = entry.name
            if (name.endsWith('.example') || name.endsWith('.template')) continue
            if (ALLOWED_EXTS.some(ext => name.endsWith(ext))) {
                await fs.copyFile(srcPath, destPath)
            }
        }
    }
}

/** Mirrors `pioEnv()` — including the offline fuse this test exists to prove. */
function pioEnv(): NodeJS.ProcessEnv {
    const dead = 'http://127.0.0.1:9'
    return {
        ...process.env,
        PYTHONPATH: path.join(RESOURCES, 'pio', 'site-packages'),
        PYTHONNOUSERSITE: '1',
        PLATFORMIO_CORE_DIR: CORE_DIR,
        PLATFORMIO_PLATFORMS_DIR: path.join(CORE_DIR, 'platforms'),
        PLATFORMIO_PACKAGES_DIR: path.join(CORE_DIR, 'packages'),
        PLATFORMIO_DISABLE_PROGRESSBAR: 'true',
        PLATFORMIO_SETTING_ENABLE_TELEMETRY: 'false',
        HTTP_PROXY: dead,
        HTTPS_PROXY: dead,
        http_proxy: dead,
        https_proxy: dead,
        NO_PROXY: '',
        no_proxy: '',
    }
}

function runPio(args: string[]): Promise<{ code: number; output: string }> {
    return new Promise((resolve, reject) => {
        const child = spawn(PYTHON, ['-m', 'platformio', ...args], { env: pioEnv() })
        let output = ''
        child.stdout.on('data', (d: Buffer) => { output += d.toString() })
        child.stderr.on('data', (d: Buffer) => { output += d.toString() })
        child.on('close', (code) => resolve({ code: code ?? -1, output }))
        child.on('error', reject)
    })
}

describe('PlatformIO integration — Mega (arduino:avr:mega)', () => {
    beforeAll(async () => {
        await fs.access(PYTHON) // run `pnpm toolchain:fetch` if this fails
        await fs.access(SOURCE_REPO)

        await fs.rm(SCRATCH_BASE, { recursive: true, force: true })
        await copySourceFiles(SOURCE_REPO, REPO)
        await fs.writeFile(path.join(REPO, 'config.h'), MEGA_CONFIG_H)
        await fs.writeFile(path.join(REPO, 'platformio.ini'), PLATFORMIO_INI)
    })

    afterAll(async () => {
        await fs.rm(SCRATCH_BASE, { recursive: true, force: true })
    })

    it(`compiles CommandStation-EX for ${FQBN} with no network access`, async () => {
        const { code, output } = await runPio(['run', '-e', 'mega2560', '--project-dir', REPO])
        // A connection failure here means something tried to download: the
        // bundled toolchain is incomplete, not that the network is down.
        expect(output, output).not.toMatch(/ProxyError|Connection refused|Failed to download/i)
        expect(output, output).toMatch(/SUCCESS|Building in .* mode/)
        expect(code, output).toBe(0)
    }, 300_000)

    it('puts build output inside the project so boards cannot collide', async () => {
        await fs.access(path.join(REPO, '.pio', 'build', 'mega2560'))
    })
})
