/**
 * Shared Playwright fixtures for DCC-Rail-Commander E2E tests.
 *
 * The `workspacePage` fixture:
 *   1. Creates an isolated temp directory for Electron userData.
 *   2. Seeds mock myRoster.h, myTurnouts.h, and config.h files on disk.
 *   3. Writes a SavedConfiguration into the preferences JSON so the home
 *      screen shows a card that can be clicked to load the workspace.
 *   4. Launches Electron with --mock-device --mock-upload --skip-startup --test-data-dir=<tmp>.
 *   5. Navigates: home → workspace (by clicking the mock config card).
 *   6. Returns the Playwright Page for the workspace view.
 *
 * Compile always runs for real, against the bundled PlatformIO toolchain — it
 * never touches hardware, so there's nothing to mock. Only upload (--mock-upload)
 * is faked, since e2e tests never have a real device to flash.
 */

import { test as base, expect } from '@playwright/test'
import { _electron as electron } from '@playwright/test'
import type { Page, ElectronApplication } from '@playwright/test'
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'fs'
import { join, resolve } from 'path'
import { tmpdir } from 'os'

/**
 * Windows can briefly hold a file handle open after Electron/PlatformIO subprocess
 * exit (antivirus/EDR real-time scanning, search indexing, delayed file-watch
 * flush), which turns a plain rmSync into an EPERM/EBUSY failure that has nothing
 * to do with test correctness. maxRetries/retryDelay are Node's built-in retry
 * for exactly this class of transient Windows error — see fs.rmSync docs.
 */
export function cleanupDir(dir: string): void {
    rmSync(dir, { recursive: true, force: true, maxRetries: 10, retryDelay: 200 })
}

// Strip ELECTRON_RUN_AS_NODE from the env passed to each Electron launch.
// When this var is set (e.g. by the Claude Code shell), Electron runs as Node.js
// and rejects Playwright's --remote-debugging-port=0 flag with "bad option".
// eslint-disable-next-line @typescript-eslint/no-unused-vars
const { ELECTRON_RUN_AS_NODE: _ern, ...ELECTRON_ENV } = process.env

// ── Mock file content ─────────────────────────────────────────────────────────

export const MOCK_ROSTER_H = [
    'ROSTER(3, "Thomas", "LIGHT/HORN/*WHISTLE/BELL")',
    'ROSTER(5, "Percy", "LIGHT/HORN")',
].join('\n')

/** Roster with a shared #define group (Thomas + Percy) and one ungrouped loco (Gordon). */
export const MOCK_ROSTER_H_GROUPED = [
    '#define STEAM_F "LIGHT/HORN/*WHISTLE/BELL" // friendlyName: "Steam Engines"',
    'ROSTER(3, "Thomas", STEAM_F)',
    'ROSTER(5, "Percy", STEAM_F)',
    'ROSTER(6, "Gordon", "LIGHT/HORN")',
].join('\n')

export const MOCK_TURNOUTS_H = [
    'SERVO_TURNOUT(200, 25, 410, 205, Slow, "Main Line Junction")',
    'SERVO_TURNOUT(201, 26, 410, 205, Fast, "Yard Entry")',
].join('\n')

/** References turnout 200 (THROW) and 201 (CLOSE) — matches MOCK_TURNOUTS_H's ids for throttle route-status E2E tests. */
export const MOCK_ROUTES_H = [
    'ROUTE(1, "Main Route")',
    'THROW(200)',
    'CLOSE(201)',
    'DONE',
].join('\n')

export const MOCK_CONFIG_H = [
    '// config.h — mock test configuration',
    '#define MAIN_DRIVER_MOTOR_SHIELD STANDARD_MOTOR_SHIELD',
].join('\n')

/** Properly-formatted config.h for visual editor round-trip tests */
export const MOCK_CONFIG_H_COMPLETE = [
    '// config.h - Generated by DCC-Rail-Commander',
    '',
    '#define IP_PORT 2560',
    '#define SCROLLMODE 1',
    '',
    '#define MOTOR_SHIELD_TYPE STANDARD_MOTOR_SHIELD',
    '',
].join('\n')

/** CSB1 config with non-stacked driver; regression fixture should normalize this to WITH_EX8874. */
export const MOCK_CONFIG_H_CSB1_BASE = [
    '// config.h - Generated by DCC-Rail-Commander',
    '',
    '#define IP_PORT 2560',
    '#define SCROLLMODE 1',
    '',
    '#define MOTOR_SHIELD_TYPE EXCSB1',
    '#define OLED_DRIVER 132,64',
    '#define WIFI_HOSTNAME "dccex"',
    '#define ENABLE_WIFI true',
    '#define WIFI_CHANNEL 1',
    '#define DISABLE_EEPROM',
    '',
].join('\n')

/**
 * Legacy-style TrackManager block with Track C/D already present. Loading this
 * does NOT by itself make the UI treat the shield as stacked — that's derived
 * solely from config.h's MOTOR_SHIELD_TYPE (see track-manager-form.ts).
 */
export const MOCK_AUTOMATION_STACKED = [
    '// myAutomation.h - Generated by DCC-Rail-Commander',
    '',
    'AUTOSTART',
    'SET_TRACK(A,MAIN)',
    'SET_TRACK(B,PROG)',
    'SET_TRACK(C,MAIN)',
    'SET_TRACK(D,MAIN)',
    'DONE',
    '',
].join('\n')

/** IOExpander myConfig.h for visual editor tests */
export const MOCK_MYCONFIG_H = [
    '// myConfig.h - Generated by DCC-Rail-Commander',
    '',
    '#define I2C_ADDRESS 0x65',
    '#define DIAG_CONFIG_DELAY 5',
    '',
].join('\n')

export const MOCK_SKETCH_INO = [
    '// CommandStation-EX.ino — minimal mock sketch',
    '#include "config.h"',
    '',
    'void setup() {}',
    'void loop() {}',
].join('\n') + '\n'

/**
 * A real product's own .cpp file, standing in for the ~60 files CommandStation-EX
 * actually ships (see quick-compile.test.ts's own doc comment on why the mock
 * sketch needs at least one of these): PlatformIO's compiledb only *describes*
 * the main .ino's preprocessed translation unit, it doesn't materialize it on
 * disk until a real build has run once, so the .ino alone can't be
 * syntax-checked — but every real product also has other .cpp files that
 * #include the same headers (config.h, myAutomation.h, ...), and those work
 * standalone. Without this, Quick Compile e2e tests would have nothing to
 * check config.h against.
 */
export const MOCK_EXTRA_CPP = [
    '// Extra.cpp — stand-in for a real product .cpp file, so config.h has a',
    '// syntax-checkable translation unit that includes it (see MOCK_SKETCH_INO)',
    '#include "config.h"',
    '',
    'void mockExtraFunction() {}',
].join('\n') + '\n'

/**
 * Reproduces the real DCC-EX/CommandStation-EX.ino's own mySetup.h hook
 * verbatim: `#if __has_include("mySetup.h") / #define SETUP(cmd) ... /
 * #include "mySetup.h" / #undef SETUP / #endif` inside setup(). mySetup.h is
 * included directly by the firmware itself here — never by myAutomation.h —
 * see config-editor-state.ts's automationPreview and its BUILTIN exclusion
 * for mySetup.h/myHal.cpp.
 */
export const MOCK_HAL_SKETCH_INO = [
    '// CommandStation-EX.ino — minimal mock sketch with the same mySetup.h',
    '// self-include hook as the real DCC-EX/CommandStation-EX.ino',
    '#include "config.h"',
    '',
    'void mockSetupCommand(const char* cmd) {}',
    '',
    'void setup() {',
    '#if __has_include("mySetup.h")',
    '  #define SETUP(cmd) mockSetupCommand(cmd)',
    '  #include "mySetup.h"',
    '  #undef SETUP',
    '#endif',
    '}',
    'void loop() {}',
].join('\n') + '\n'

export const MOCK_SETUP_H = [
    '// mySetup.h — one-off startup commands, included directly by the',
    '// firmware\'s own setup() (see MOCK_HAL_SKETCH_INO), not by myAutomation.h',
    'SETUP("<D CMD>");',
].join('\n') + '\n'

/**
 * Matches the real file's own doc comment: "if the file has a .cpp extension
 * it WILL be compiled into the build and the halSetup() function WILL be
 * invoked" — a plain translation unit PlatformIO's src_dir glob compiles
 * directly, no #include required anywhere.
 */
export const MOCK_HAL_CPP = [
    '// myHal.cpp — HAL device setup, compiled directly by PlatformIO as its',
    '// own translation unit (see the doc comment at the top of the real file)',
    'void halSetup() {}',
].join('\n') + '\n'

/**
 * Deliberately EXRAIL-macro-free (this synthetic sketch has no real EXRAIL.h)
 * — just enough real content to prove myAutomation.h itself compiles cleanly
 * when actually #included by another translation unit (see MOCK_EXRAIL_MOCK_CPP).
 */
export const MOCK_AUTOMATION_MINIMAL = [
    '// myAutomation.h - imported project',
    '// Custom EXRAIL commands would normally go here.',
].join('\n') + '\n'

/**
 * Stands in for two real CommandStation-EX files at once: EXRAIL2.cpp (which
 * #include "myAutomation.h") and IODevice.cpp (which declares and invokes
 * halSetup() via a weak symbol). Exists so myAutomation.h is actually
 * compiled as part of this test — if a regression ever reintroduced
 * `#include "myHal.cpp"` into myAutomation.h's generated content, this file's
 * own halSetup() extern would collide with myHal.cpp's real one at link time
 * ("multiple definition of halSetup()"), and a reintroduced
 * `#include "mySetup.h"` would fail to compile here (SETUP is only ever
 * macro-defined around the .ino's own inclusion, not this one).
 */
export const MOCK_EXRAIL_MOCK_CPP = [
    '// ExrailMock.cpp — stand-in for EXRAIL2.cpp + IODevice.cpp\'s halSetup()',
    '// weak-symbol hook (see MOCK_AUTOMATION_MINIMAL\'s doc comment)',
    '#include "config.h"',
    '#include "myAutomation.h"',
    '',
    'extern void halSetup();',
    'void invokeHalSetup() { halSetup(); }',
].join('\n') + '\n'

// Resolve Electron main entry relative to repo root (tests/e2e/ → ../../out/main/index.js)
const ELECTRON_MAIN = resolve(__dirname, '../../out/main/index.js')

// ── Fixture types ─────────────────────────────────────────────────────────────

interface WorkspaceFixtures {
    electronApp: ElectronApplication
    workspacePage: Page
    csb1StackedApp: ElectronApplication
    csb1StackedPage: Page
    importedHalProjectApp: ElectronApplication
    importedHalProjectPage: Page
    duplicateAutomationApp: ElectronApplication
    duplicateAutomationPage: Page
    ioExpanderApp: ElectronApplication
    ioExpanderPage: Page
    rosterGroupedApp: ElectronApplication
    rosterGroupedPage: Page
    onboardingApp: ElectronApplication
    onboardingPage: Page
    manySavedConfigsApp: ElectronApplication
    manySavedConfigsPage: Page
}

// ── Shared: seed temp dir + launch Electron ───────────────────────────────────

async function launchApp(): Promise<{ app: ElectronApplication; testDataDir: string }> {
    const testDataDir = mkdtempSync(join(tmpdir(), 'dcc-rail-commander-e2e-'))

    const scratchPath = join(testDataDir, 'scratch', 'CommandStation-EX')
    mkdirSync(scratchPath, { recursive: true })
    writeFileSync(join(scratchPath, 'myRoster.h'), MOCK_ROSTER_H, 'utf-8')
    writeFileSync(join(scratchPath, 'myTurnouts.h'), MOCK_TURNOUTS_H, 'utf-8')
    writeFileSync(join(scratchPath, 'myRoutes.h'), MOCK_ROUTES_H, 'utf-8')
    writeFileSync(join(scratchPath, 'config.h'), MOCK_CONFIG_H, 'utf-8')
    writeFileSync(join(scratchPath, 'CommandStation-EX.ino'), MOCK_SKETCH_INO, 'utf-8')
    writeFileSync(join(scratchPath, 'Extra.cpp'), MOCK_EXTRA_CPP, 'utf-8')

    const prefsDir = join(testDataDir, 'app-preferences')
    mkdirSync(prefsDir, { recursive: true })
    const savedConfig = {
        id: 'e2e-test-config',
        name: 'E2E Test Layout',
        deviceName: 'Arduino Mega 2560',
        devicePort: '/dev/ttyACM1',
        deviceFqbn: 'arduino:avr:mega:cpu=atmega2560',
        product: 'ex_commandstation',
        productName: 'EX-CommandStation',
        version: 'v5.4.0-Prod',
        repoPath: join(testDataDir, 'scratch'),
        scratchPath,
        configFiles: [
            { name: 'config.h', content: MOCK_CONFIG_H },
            { name: 'myRoster.h', content: MOCK_ROSTER_H },
            { name: 'myTurnouts.h', content: MOCK_TURNOUTS_H },
            { name: 'myRoutes.h', content: MOCK_ROUTES_H },
        ],
        lastModified: new Date().toISOString(),
    }
    writeFileSync(
        join(prefsDir, 'dcc-rail-commander-preferences.json'),
        JSON.stringify({ savedConfigurations: [savedConfig] }, null, 2),
        'utf-8',
    )

    const args = [
        ELECTRON_MAIN,
        '--mock-device',
        '--mock-upload',
        '--skip-startup',
        `--test-data-dir=${testDataDir}`,
        '--disable-gpu',
        '--no-sandbox',
        '--offscreen',
        '--js-flags=--no-expose-wasm',
    ]

    const app = await electron.launch({ args, chromiumSandbox: false, env: ELECTRON_ENV })
    return { app, testDataDir }
}

async function navigateToWorkspace(app: ElectronApplication): Promise<Page> {
    const page = await app.firstWindow()
    page.on('dialog', (dialog) => dialog.accept().catch(() => undefined))
    await page.waitForLoadState('domcontentloaded')
    await page.evaluate(() => {
        document.querySelectorAll('[id^="ej2-licensing"]').forEach(el => el.remove())
    }).catch(() => undefined)
    await expect(page.getByText('E2E Test Layout')).toBeVisible({ timeout: 15_000 })
    await page.getByText('E2E Test Layout').click()
    await expect(page.getByText('Roster', { exact: true })).toBeVisible({ timeout: 10_000 })
    return page
}

async function launchIOExpanderApp(): Promise<{ app: ElectronApplication; testDataDir: string }> {
    const testDataDir = mkdtempSync(join(tmpdir(), 'dcc-rail-commander-e2e-iox-'))

    const scratchPath = join(testDataDir, 'scratch', 'EX-IOExpander')
    mkdirSync(scratchPath, { recursive: true })
    writeFileSync(join(scratchPath, 'myConfig.h'), MOCK_MYCONFIG_H, 'utf-8')

    const prefsDir = join(testDataDir, 'app-preferences')
    mkdirSync(prefsDir, { recursive: true })
    const savedConfig = {
        id: 'e2e-iox-config',
        name: 'E2E Test Layout',
        deviceName: 'Arduino Nano',
        devicePort: '/dev/ttyUSB0',
        deviceFqbn: 'arduino:avr:nano:cpu=atmega328',
        product: 'ex_ioexpander',
        productName: 'EX-IOExpander',
        version: 'v0.6.0',
        repoPath: join(testDataDir, 'scratch'),
        scratchPath,
        configFiles: [
            { name: 'myConfig.h', content: MOCK_MYCONFIG_H },
        ],
        lastModified: new Date().toISOString(),
    }
    writeFileSync(
        join(prefsDir, 'dcc-rail-commander-preferences.json'),
        JSON.stringify({ savedConfigurations: [savedConfig] }, null, 2),
        'utf-8',
    )

    const args = [
        ELECTRON_MAIN,
        '--mock-device',
        '--mock-upload',
        '--skip-startup',
        `--test-data-dir=${testDataDir}`,
        '--disable-gpu',
        '--no-sandbox',
        '--offscreen',
        '--js-flags=--no-expose-wasm',
    ]

    const app = await electron.launch({ args, chromiumSandbox: false, env: ELECTRON_ENV })
    return { app, testDataDir }
}

async function launchRosterGroupedApp(): Promise<{ app: ElectronApplication; testDataDir: string }> {
    const testDataDir = mkdtempSync(join(tmpdir(), 'dcc-rail-commander-e2e-grp-'))

    const scratchPath = join(testDataDir, 'scratch', 'CommandStation-EX')
    mkdirSync(scratchPath, { recursive: true })
    writeFileSync(join(scratchPath, 'myRoster.h'), MOCK_ROSTER_H_GROUPED, 'utf-8')
    writeFileSync(join(scratchPath, 'myTurnouts.h'), MOCK_TURNOUTS_H, 'utf-8')
    writeFileSync(join(scratchPath, 'config.h'), MOCK_CONFIG_H, 'utf-8')
    writeFileSync(join(scratchPath, 'CommandStation-EX.ino'), MOCK_SKETCH_INO, 'utf-8')

    const prefsDir = join(testDataDir, 'app-preferences')
    mkdirSync(prefsDir, { recursive: true })
    const savedConfig = {
        id: 'e2e-grouped-roster',
        name: 'E2E Test Layout',
        deviceName: 'Arduino Mega 2560',
        devicePort: '/dev/ttyACM1',
        deviceFqbn: 'arduino:avr:mega:cpu=atmega2560',
        product: 'ex_commandstation',
        productName: 'EX-CommandStation',
        version: 'v5.4.0-Prod',
        repoPath: join(testDataDir, 'scratch'),
        scratchPath,
        configFiles: [
            { name: 'config.h', content: MOCK_CONFIG_H },
            { name: 'myRoster.h', content: MOCK_ROSTER_H_GROUPED },
            { name: 'myTurnouts.h', content: MOCK_TURNOUTS_H },
        ],
        lastModified: new Date().toISOString(),
    }
    writeFileSync(
        join(prefsDir, 'dcc-rail-commander-preferences.json'),
        JSON.stringify({ savedConfigurations: [savedConfig] }, null, 2),
        'utf-8',
    )

    const args = [
        ELECTRON_MAIN,
        '--mock-device',
        '--mock-upload',
        '--skip-startup',
        `--test-data-dir=${testDataDir}`,
        '--disable-gpu',
        '--no-sandbox',
        '--offscreen',
        '--js-flags=--no-expose-wasm',
    ]

    const app = await electron.launch({ args, chromiumSandbox: false, env: ELECTRON_ENV })
    return { app, testDataDir }
}

async function launchCsb1StackedApp(): Promise<{ app: ElectronApplication; testDataDir: string }> {
    const testDataDir = mkdtempSync(join(tmpdir(), 'dcc-rail-commander-e2e-csb1-'))

    const scratchPath = join(testDataDir, 'scratch', 'CommandStation-EX')
    mkdirSync(scratchPath, { recursive: true })
    writeFileSync(join(scratchPath, 'myRoster.h'), MOCK_ROSTER_H, 'utf-8')
    writeFileSync(join(scratchPath, 'myTurnouts.h'), MOCK_TURNOUTS_H, 'utf-8')
    writeFileSync(join(scratchPath, 'config.h'), MOCK_CONFIG_H_CSB1_BASE, 'utf-8')
    writeFileSync(join(scratchPath, 'myAutomation.h'), MOCK_AUTOMATION_STACKED, 'utf-8')
    writeFileSync(join(scratchPath, 'CommandStation-EX.ino'), MOCK_SKETCH_INO, 'utf-8')

    const prefsDir = join(testDataDir, 'app-preferences')
    mkdirSync(prefsDir, { recursive: true })
    const savedConfig = {
        id: 'e2e-csb1-stacked',
        name: 'E2E Test Layout',
        deviceName: 'EX-CSB1',
        devicePort: '/dev/ttyUSB9',
        deviceFqbn: 'esp32:esp32:esp32',
        product: 'ex_commandstation',
        productName: 'EX-CommandStation',
        version: 'v5.4.0-Prod',
        repoPath: join(testDataDir, 'scratch'),
        scratchPath,
        configFiles: [
            { name: 'config.h', content: MOCK_CONFIG_H_CSB1_BASE },
            { name: 'myAutomation.h', content: MOCK_AUTOMATION_STACKED },
            { name: 'myRoster.h', content: MOCK_ROSTER_H },
            { name: 'myTurnouts.h', content: MOCK_TURNOUTS_H },
        ],
        lastModified: new Date().toISOString(),
    }
    writeFileSync(
        join(prefsDir, 'dcc-rail-commander-preferences.json'),
        JSON.stringify({ savedConfigurations: [savedConfig] }, null, 2),
        'utf-8',
    )

    const args = [
        ELECTRON_MAIN,
        '--mock-device',
        '--mock-upload',
        '--skip-startup',
        `--test-data-dir=${testDataDir}`,
        '--disable-gpu',
        '--no-sandbox',
        '--offscreen',
        '--js-flags=--no-expose-wasm',
    ]

    const app = await electron.launch({ args, chromiumSandbox: false, env: ELECTRON_ENV })
    return { app, testDataDir }
}

// ── Imported project with mySetup.h + myHal.cpp (real DCC-EX self-include hazards) ──

async function launchImportedHalProjectApp(): Promise<{ app: ElectronApplication; testDataDir: string }> {
    const testDataDir = mkdtempSync(join(tmpdir(), 'dcc-rail-commander-e2e-hal-import-'))

    const scratchPath = join(testDataDir, 'scratch', 'CommandStation-EX')
    mkdirSync(scratchPath, { recursive: true })
    writeFileSync(join(scratchPath, 'config.h'), MOCK_CONFIG_H, 'utf-8')
    writeFileSync(join(scratchPath, 'mySetup.h'), MOCK_SETUP_H, 'utf-8')
    writeFileSync(join(scratchPath, 'myHal.cpp'), MOCK_HAL_CPP, 'utf-8')
    writeFileSync(join(scratchPath, 'myAutomation.h'), MOCK_AUTOMATION_MINIMAL, 'utf-8')
    writeFileSync(join(scratchPath, 'CommandStation-EX.ino'), MOCK_HAL_SKETCH_INO, 'utf-8')
    writeFileSync(join(scratchPath, 'ExrailMock.cpp'), MOCK_EXRAIL_MOCK_CPP, 'utf-8')

    const prefsDir = join(testDataDir, 'app-preferences')
    mkdirSync(prefsDir, { recursive: true })
    const savedConfig = {
        id: 'e2e-hal-import',
        name: 'E2E Test Layout',
        deviceName: 'Arduino Mega 2560',
        devicePort: '/dev/ttyACM1',
        deviceFqbn: 'arduino:avr:mega:cpu=atmega2560',
        product: 'ex_commandstation',
        productName: 'EX-CommandStation',
        version: 'v5.4.0-Prod',
        repoPath: join(testDataDir, 'scratch'),
        scratchPath,
        configFiles: [
            { name: 'config.h', content: MOCK_CONFIG_H },
            { name: 'mySetup.h', content: MOCK_SETUP_H },
            { name: 'myHal.cpp', content: MOCK_HAL_CPP },
            { name: 'myAutomation.h', content: MOCK_AUTOMATION_MINIMAL },
        ],
        lastModified: new Date().toISOString(),
    }
    writeFileSync(
        join(prefsDir, 'dcc-rail-commander-preferences.json'),
        JSON.stringify({ savedConfigurations: [savedConfig] }, null, 2),
        'utf-8',
    )

    const args = [
        ELECTRON_MAIN,
        '--mock-device',
        '--mock-upload',
        '--skip-startup',
        `--test-data-dir=${testDataDir}`,
        '--disable-gpu',
        '--no-sandbox',
        '--offscreen',
        '--js-flags=--no-expose-wasm',
    ]

    const app = await electron.launch({ args, chromiumSandbox: false, env: ELECTRON_ENV })
    return { app, testDataDir }
}

// ── myAutomation.h with a duplicate AUTOSTART SEQUENCE(id) — Duplicate Automation Blocks dialog ──

/** SEQUENCE(96) is declared twice — the exact shape CommandStation-EX's own seqCount() check rejects. */
export const MOCK_AUTOMATION_DUPLICATE_SEQUENCE = [
    'AUTOSTART SEQUENCE(96)',
    'SET(110)',
    'FOLLOW(96)',
    '',
    'AUTOSTART SEQUENCE(96)',
    'SET(111) //bm',
    'FOLLOW(96)',
].join('\n') + '\n'

async function launchDuplicateAutomationApp(): Promise<{ app: ElectronApplication; testDataDir: string }> {
    const testDataDir = mkdtempSync(join(tmpdir(), 'dcc-rail-commander-e2e-dup-automation-'))

    const scratchPath = join(testDataDir, 'scratch', 'CommandStation-EX')
    mkdirSync(scratchPath, { recursive: true })
    writeFileSync(join(scratchPath, 'config.h'), MOCK_CONFIG_H, 'utf-8')
    writeFileSync(join(scratchPath, 'myAutomation.h'), MOCK_AUTOMATION_DUPLICATE_SEQUENCE, 'utf-8')

    const prefsDir = join(testDataDir, 'app-preferences')
    mkdirSync(prefsDir, { recursive: true })
    const savedConfig = {
        id: 'e2e-dup-automation',
        name: 'E2E Test Layout',
        deviceName: 'Arduino Mega 2560',
        devicePort: '/dev/ttyACM1',
        deviceFqbn: 'arduino:avr:mega:cpu=atmega2560',
        product: 'ex_commandstation',
        productName: 'EX-CommandStation',
        version: 'v5.4.0-Prod',
        repoPath: join(testDataDir, 'scratch'),
        scratchPath,
        configFiles: [
            { name: 'config.h', content: MOCK_CONFIG_H },
            { name: 'myAutomation.h', content: MOCK_AUTOMATION_DUPLICATE_SEQUENCE },
        ],
        lastModified: new Date().toISOString(),
    }
    writeFileSync(
        join(prefsDir, 'dcc-rail-commander-preferences.json'),
        JSON.stringify({ savedConfigurations: [savedConfig] }, null, 2),
        'utf-8',
    )

    const args = [
        ELECTRON_MAIN,
        '--mock-device',
        '--mock-upload',
        '--skip-startup',
        `--test-data-dir=${testDataDir}`,
        '--disable-gpu',
        '--no-sandbox',
        '--offscreen',
        '--js-flags=--no-expose-wasm',
    ]

    const app = await electron.launch({ args, chromiumSandbox: false, env: ELECTRON_ENV })
    return { app, testDataDir }
}

// ── Onboarding (home screen, no saved configs) — drives the "New Device" wizard ──

async function launchOnboardingApp(): Promise<{ app: ElectronApplication; testDataDir: string }> {
    const testDataDir = mkdtempSync(join(tmpdir(), 'dcc-rail-commander-e2e-onboarding-'))

    const args = [
        ELECTRON_MAIN,
        '--mock-device',
        '--mock-upload',
        '--skip-startup',
        `--test-data-dir=${testDataDir}`,
        '--disable-gpu',
        '--no-sandbox',
        '--offscreen',
        '--js-flags=--no-expose-wasm',
    ]

    const app = await electron.launch({ args, chromiumSandbox: false, env: ELECTRON_ENV })
    return { app, testDataDir }
}

async function navigateToOnboarding(app: ElectronApplication): Promise<Page> {
    const page = await app.firstWindow()
    page.on('dialog', (dialog) => dialog.accept().catch(() => undefined))
    await page.waitForLoadState('domcontentloaded')
    await page.evaluate(() => {
        document.querySelectorAll('[id^="ej2-licensing"]').forEach(el => el.remove())
    }).catch(() => undefined)
    await expect(page.getByText('New Device', { exact: true })).toBeVisible({ timeout: 15_000 })
    return page
}

// ── Home screen with many saved configs (small-window overflow regression) ────

async function launchManySavedConfigsApp(): Promise<{ app: ElectronApplication; testDataDir: string }> {
    const testDataDir = mkdtempSync(join(tmpdir(), 'dcc-rail-commander-e2e-many-configs-'))

    const prefsDir = join(testDataDir, 'app-preferences')
    mkdirSync(prefsDir, { recursive: true })
    // Enough cards to overflow the app's 900x600 minimum window size several times over —
    // see small-window.spec.ts's Home-screen test.
    const savedConfigurations = Array.from({ length: 14 }, (_, i) => ({
        id: `many-cfg-${i}`,
        name: `Layout ${i + 1}`,
        deviceName: 'Arduino Mega 2560',
        devicePort: `/dev/ttyACM${i}`,
        deviceFqbn: 'arduino:avr:mega:cpu=atmega2560',
        product: 'ex_commandstation',
        productName: 'EX-CommandStation',
        version: 'v5.4.0-Prod',
        repoPath: join(testDataDir, `scratch-${i}`),
        scratchPath: join(testDataDir, `scratch-${i}`),
        configFiles: [{ name: 'config.h', content: MOCK_CONFIG_H }],
        lastModified: new Date().toISOString(),
    }))
    writeFileSync(
        join(prefsDir, 'dcc-rail-commander-preferences.json'),
        JSON.stringify({ savedConfigurations }, null, 2),
        'utf-8',
    )

    const args = [
        ELECTRON_MAIN,
        '--mock-device',
        '--mock-upload',
        '--skip-startup',
        `--test-data-dir=${testDataDir}`,
        '--disable-gpu',
        '--no-sandbox',
        '--offscreen',
        '--js-flags=--no-expose-wasm',
    ]

    const app = await electron.launch({ args, chromiumSandbox: false, env: ELECTRON_ENV })
    return { app, testDataDir }
}

async function navigateToManySavedConfigs(app: ElectronApplication): Promise<Page> {
    const page = await app.firstWindow()
    page.on('dialog', (dialog) => dialog.accept().catch(() => undefined))
    await page.waitForLoadState('domcontentloaded')
    await page.evaluate(() => {
        document.querySelectorAll('[id^="ej2-licensing"]').forEach(el => el.remove())
    }).catch(() => undefined)
    await expect(page.getByText('Layout 1', { exact: true })).toBeVisible({ timeout: 15_000 })
    return page
}

// ── Shared test base with workspace fixtures ──────────────────────────────────

async function navigateToIOExpanderWorkspace(app: ElectronApplication): Promise<Page> {
    const page = await app.firstWindow()
    page.on('dialog', (dialog) => dialog.accept().catch(() => undefined))
    await page.waitForLoadState('domcontentloaded')
    await page.evaluate(() => {
        document.querySelectorAll('[id^="ej2-licensing"]').forEach(el => el.remove())
    }).catch(() => undefined)
    await expect(page.getByText('E2E Test Layout')).toBeVisible({ timeout: 15_000 })
    await page.getByText('E2E Test Layout').click()
    // IOExpander has no Roster; wait for the config file tab instead.
    // Use .first() because 'myConfig.h' also appears in the file content area.
    await expect(page.getByText('myConfig.h').first()).toBeVisible({ timeout: 10_000 })
    return page
}

export const test = base.extend<WorkspaceFixtures>({
    // eslint-disable-next-line no-empty-pattern
    electronApp: async ({ }, use) => {
        const { app, testDataDir } = await launchApp()
        await use(app)
        await app.close()
        cleanupDir(testDataDir)
    },

    workspacePage: async ({ electronApp }, use) => {
        await use(await navigateToWorkspace(electronApp))
    },

    // ── CSB1 stacked-shield regression workspace ───────────────────────────
    // eslint-disable-next-line no-empty-pattern
    csb1StackedApp: async ({ }, use) => {
        const { app, testDataDir } = await launchCsb1StackedApp()
        await use(app)
        await app.close()
        cleanupDir(testDataDir)
    },

    csb1StackedPage: async ({ csb1StackedApp }, use) => {
        await use(await navigateToWorkspace(csb1StackedApp))
    },

    // ── Imported project with mySetup.h + myHal.cpp ─────────────────────────
    // eslint-disable-next-line no-empty-pattern
    importedHalProjectApp: async ({ }, use) => {
        const { app, testDataDir } = await launchImportedHalProjectApp()
        await use(app)
        await app.close()
        cleanupDir(testDataDir)
    },

    importedHalProjectPage: async ({ importedHalProjectApp }, use) => {
        await use(await navigateToWorkspace(importedHalProjectApp))
    },

    // ── Duplicate Automation Blocks dialog ──────────────────────────────────
    // eslint-disable-next-line no-empty-pattern
    duplicateAutomationApp: async ({ }, use) => {
        const { app, testDataDir } = await launchDuplicateAutomationApp()
        await use(app)
        await app.close()
        cleanupDir(testDataDir)
    },

    duplicateAutomationPage: async ({ duplicateAutomationApp }, use) => {
        await use(await navigateToWorkspace(duplicateAutomationApp))
    },

    // ── IOExpander workspace ──────────────────────────────────────────────────
    // eslint-disable-next-line no-empty-pattern
    ioExpanderApp: async ({ }, use) => {
        const { app, testDataDir } = await launchIOExpanderApp()
        await use(app)
        await app.close()
        cleanupDir(testDataDir)
    },

    ioExpanderPage: async ({ ioExpanderApp }, use) => {
        await use(await navigateToIOExpanderWorkspace(ioExpanderApp))
    },

    // ── Grouped roster workspace ──────────────────────────────────────────────
    // eslint-disable-next-line no-empty-pattern
    rosterGroupedApp: async ({ }, use) => {
        const { app, testDataDir } = await launchRosterGroupedApp()
        await use(app)
        await app.close()
        cleanupDir(testDataDir)
    },

    rosterGroupedPage: async ({ rosterGroupedApp }, use) => {
        await use(await navigateToWorkspace(rosterGroupedApp))
    },

    // ── Onboarding / "New Device" wizard ────────────────────────────────────
    // eslint-disable-next-line no-empty-pattern
    onboardingApp: async ({ }, use) => {
        const { app, testDataDir } = await launchOnboardingApp()
        await use(app)
        await app.close()
        cleanupDir(testDataDir)
    },

    onboardingPage: async ({ onboardingApp }, use) => {
        await use(await navigateToOnboarding(onboardingApp))
    },

    // ── Home screen with many saved configs ─────────────────────────────────
    // eslint-disable-next-line no-empty-pattern
    manySavedConfigsApp: async ({ }, use) => {
        const { app, testDataDir } = await launchManySavedConfigsApp()
        await use(app)
        await app.close()
        cleanupDir(testDataDir)
    },

    manySavedConfigsPage: async ({ manySavedConfigsApp }, use) => {
        await use(await navigateToManySavedConfigs(manySavedConfigsApp))
    },
})

export { expect }
