/**
 * Shared Playwright fixtures for DCC-Rail-Commander E2E tests.
 *
 * The `workspacePage` fixture:
 *   1. Creates an isolated temp directory for Electron userData.
 *   2. Seeds mock myRoster.h, myTurnouts.h, and config.h files on disk.
 *   3. Writes a SavedConfiguration into the preferences JSON so the home
 *      screen shows a card that can be clicked to load the workspace.
 *   4. Launches Electron with --mock-device --mock-upload --skip-startup --test-data-dir=<tmp>.
 *   5. Navigates: home → workspace (by clicking the mock config card).
 *   6. Returns the Playwright Page for the workspace view.
 *
 * Compile always runs for real, against the bundled PlatformIO toolchain — it
 * never touches hardware, so there's nothing to mock. Only upload (--mock-upload)
 * is faked, since e2e tests never have a real device to flash.
 */

import { test as base, expect } from '@playwright/test'
import { _electron as electron } from '@playwright/test'
import type { Page, ElectronApplication } from '@playwright/test'
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'fs'
import { join, resolve } from 'path'
import { tmpdir } from 'os'

/**
 * Windows can briefly hold a file handle open after Electron/PlatformIO subprocess
 * exit (antivirus/EDR real-time scanning, search indexing, delayed file-watch
 * flush), which turns a plain rmSync into an EPERM/EBUSY failure that has nothing
 * to do with test correctness. maxRetries/retryDelay are Node's built-in retry
 * for exactly this class of transient Windows error — see fs.rmSync docs.
 */
export function cleanupDir(dir: string): void {
    rmSync(dir, { recursive: true, force: true, maxRetries: 10, retryDelay: 200 })
}

// Strip ELECTRON_RUN_AS_NODE from the env passed to each Electron launch.
// When this var is set (e.g. by the Claude Code shell), Electron runs as Node.js
// and rejects Playwright's --remote-debugging-port=0 flag with "bad option".
// eslint-disable-next-line @typescript-eslint/no-unused-vars
const { ELECTRON_RUN_AS_NODE: _ern, ...ELECTRON_ENV } = process.env

// ── Mock file content ─────────────────────────────────────────────────────────

export const MOCK_ROSTER_H = [
    'ROSTER(3, "Thomas", "LIGHT/HORN/*WHISTLE/BELL")',
    'ROSTER(5, "Percy", "LIGHT/HORN")',
].join('\n')

/** Roster with a shared #define group (Thomas + Percy) and one ungrouped loco (Gordon). */
export const MOCK_ROSTER_H_GROUPED = [
    '#define STEAM_F "LIGHT/HORN/*WHISTLE/BELL" // friendlyName: "Steam Engines"',
    'ROSTER(3, "Thomas", STEAM_F)',
    'ROSTER(5, "Percy", STEAM_F)',
    'ROSTER(6, "Gordon", "LIGHT/HORN")',
].join('\n')

export const MOCK_TURNOUTS_H = [
    'SERVO_TURNOUT(200, 25, 410, 205, Slow, "Main Line Junction")',
    'SERVO_TURNOUT(201, 26, 410, 205, Fast, "Yard Entry")',
].join('\n')

/** References turnout 200 (THROW) and 201 (CLOSE) — matches MOCK_TURNOUTS_H's ids for throttle route-status E2E tests. */
export const MOCK_ROUTES_H = [
    'ROUTE(1, "Main Route")',
    'THROW(200)',
    'CLOSE(201)',
    'DONE',
].join('\n')

export const MOCK_CONFIG_H = [
    '// config.h — mock test configuration',
    '#define MAIN_DRIVER_MOTOR_SHIELD STANDARD_MOTOR_SHIELD',
].join('\n')

/** Properly-formatted config.h for visual editor round-trip tests */
export const MOCK_CONFIG_H_COMPLETE = [
    '// config.h - Generated by DCC-Rail-Commander',
    '',
    '#define IP_PORT 2560',
    '#define SCROLLMODE 1',
    '',
    '#define MOTOR_SHIELD_TYPE STANDARD_MOTOR_SHIELD',
    '',
].join('\n')

/** CSB1 config with non-stacked driver; regression fixture should normalize this to WITH_EX8874. */
export const MOCK_CONFIG_H_CSB1_BASE = [
    '// config.h - Generated by DCC-Rail-Commander',
    '',
    '#define IP_PORT 2560',
    '#define SCROLLMODE 1',
    '',
    '#define MOTOR_SHIELD_TYPE EXCSB1',
    '#define OLED_DRIVER 132,64',
    '#define WIFI_HOSTNAME "dccex"',
    '#define ENABLE_WIFI true',
    '#define WIFI_CHANNEL 1',
    '#define DISABLE_EEPROM',
    '',
].join('\n')

/**
 * Legacy-style TrackManager block with Track C/D already present. Loading this
 * does NOT by itself make the UI treat the shield as stacked — that's derived
 * solely from config.h's MOTOR_SHIELD_TYPE (see track-manager-form.ts).
 */
export const MOCK_AUTOMATION_STACKED = [
    '// myAutomation.h - Generated by DCC-Rail-Commander',
    '',
    'AUTOSTART',
    'SET_TRACK(A,MAIN)',
    'SET_TRACK(B,PROG)',
    'SET_TRACK(C,MAIN)',
    'SET_TRACK(D,MAIN)',
    'DONE',
    '',
].join('\n')

/** IOExpander myConfig.h for visual editor tests */
export const MOCK_MYCONFIG_H = [
    '// myConfig.h - Generated by DCC-Rail-Commander',
    '',
    '#define I2C_ADDRESS 0x65',
    '#define DIAG_CONFIG_DELAY 5',
    '',
].join('\n')

export const MOCK_SKETCH_INO = [
    '// CommandStation-EX.ino — minimal mock sketch',
    '#include "config.h"',
    '',
    'void setup() {}',
    'void loop() {}',
].join('\n') + '\n'

/**
 * A real product's own .cpp file, standing in for the ~60 files CommandStation-EX
 * actually ships (see quick-compile.test.ts's own doc comment on why the mock
 * sketch needs at least one of these): PlatformIO's compiledb only *describes*
 * the main .ino's preprocessed translation unit, it doesn't materialize it on
 * disk until a real build has run once, so the .ino alone can't be
 * syntax-checked — but every real product also has other .cpp files that
 * #include the same headers (config.h, myAutomation.h, ...), and those work
 * standalone. Without this, Quick Compile e2e tests would have nothing to
 * check config.h against.
 */
export const MOCK_EXTRA_CPP = [
    '// Extra.cpp — stand-in for a real product .cpp file, so config.h has a',
    '// syntax-checkable translation unit that includes it (see MOCK_SKETCH_INO)',
    '#include "config.h"',
    '',
    'void mockExtraFunction() {}',
].join('\n') + '\n'

// Resolve Electron main entry relative to repo root (tests/e2e/ → ../../out/main/index.js)
const ELECTRON_MAIN = resolve(__dirname, '../../out/main/index.js')

// ── Fixture types ─────────────────────────────────────────────────────────────

interface WorkspaceFixtures {
    electronApp: ElectronApplication
    workspacePage: Page
    csb1StackedApp: ElectronApplication
    csb1StackedPage: Page
    ioExpanderApp: ElectronApplication
    ioExpanderPage: Page
    rosterGroupedApp: ElectronApplication
    rosterGroupedPage: Page
    onboardingApp: ElectronApplication
    onboardingPage: Page
}

// ── Shared: seed temp dir + launch Electron ───────────────────────────────────

async function launchApp(): Promise<{ app: ElectronApplication; testDataDir: string }> {
    const testDataDir = mkdtempSync(join(tmpdir(), 'dcc-rail-commander-e2e-'))

    const scratchPath = join(testDataDir, 'scratch', 'CommandStation-EX')
    mkdirSync(scratchPath, { recursive: true })
    writeFileSync(join(scratchPath, 'myRoster.h'), MOCK_ROSTER_H, 'utf-8')
    writeFileSync(join(scratchPath, 'myTurnouts.h'), MOCK_TURNOUTS_H, 'utf-8')
    writeFileSync(join(scratchPath, 'myRoutes.h'), MOCK_ROUTES_H, 'utf-8')
    writeFileSync(join(scratchPath, 'config.h'), MOCK_CONFIG_H, 'utf-8')
    writeFileSync(join(scratchPath, 'CommandStation-EX.ino'), MOCK_SKETCH_INO, 'utf-8')
    writeFileSync(join(scratchPath, 'Extra.cpp'), MOCK_EXTRA_CPP, 'utf-8')

    const prefsDir = join(testDataDir, 'app-preferences')
    mkdirSync(prefsDir, { recursive: true })
    const savedConfig = {
        id: 'e2e-test-config',
        name: 'E2E Test Layout',
        deviceName: 'Arduino Mega 2560',
        devicePort: '/dev/ttyACM1',
        deviceFqbn: 'arduino:avr:mega:cpu=atmega2560',
        product: 'ex_commandstation',
        productName: 'EX-CommandStation',
        version: 'v5.4.0-Prod',
        repoPath: join(testDataDir, 'scratch'),
        scratchPath,
        configFiles: [
            { name: 'config.h', content: MOCK_CONFIG_H },
            { name: 'myRoster.h', content: MOCK_ROSTER_H },
            { name: 'myTurnouts.h', content: MOCK_TURNOUTS_H },
            { name: 'myRoutes.h', content: MOCK_ROUTES_H },
        ],
        lastModified: new Date().toISOString(),
    }
    writeFileSync(
        join(prefsDir, 'dcc-rail-commander-preferences.json'),
        JSON.stringify({ savedConfigurations: [savedConfig] }, null, 2),
        'utf-8',
    )

    const args = [
        ELECTRON_MAIN,
        '--mock-device',
        '--mock-upload',
        '--skip-startup',
        `--test-data-dir=${testDataDir}`,
        '--disable-gpu',
        '--no-sandbox',
        '--offscreen',
        '--js-flags=--no-expose-wasm',
    ]

    const app = await electron.launch({ args, chromiumSandbox: false, env: ELECTRON_ENV })
    return { app, testDataDir }
}

async function navigateToWorkspace(app: ElectronApplication): Promise<Page> {
    const page = await app.firstWindow()
    page.on('dialog', (dialog) => dialog.accept().catch(() => undefined))
    await page.waitForLoadState('domcontentloaded')
    await page.evaluate(() => {
        document.querySelectorAll('[id^="ej2-licensing"]').forEach(el => el.remove())
    }).catch(() => undefined)
    await expect(page.getByText('E2E Test Layout')).toBeVisible({ timeout: 15_000 })
    await page.getByText('E2E Test Layout').click()
    await expect(page.getByText('Roster', { exact: true })).toBeVisible({ timeout: 10_000 })
    return page
}

async function launchIOExpanderApp(): Promise<{ app: ElectronApplication; testDataDir: string }> {
    const testDataDir = mkdtempSync(join(tmpdir(), 'dcc-rail-commander-e2e-iox-'))

    const scratchPath = join(testDataDir, 'scratch', 'EX-IOExpander')
    mkdirSync(scratchPath, { recursive: true })
    writeFileSync(join(scratchPath, 'myConfig.h'), MOCK_MYCONFIG_H, 'utf-8')

    const prefsDir = join(testDataDir, 'app-preferences')
    mkdirSync(prefsDir, { recursive: true })
    const savedConfig = {
        id: 'e2e-iox-config',
        name: 'E2E Test Layout',
        deviceName: 'Arduino Nano',
        devicePort: '/dev/ttyUSB0',
        deviceFqbn: 'arduino:avr:nano:cpu=atmega328',
        product: 'ex_ioexpander',
        productName: 'EX-IOExpander',
        version: 'v0.6.0',
        repoPath: join(testDataDir, 'scratch'),
        scratchPath,
        configFiles: [
            { name: 'myConfig.h', content: MOCK_MYCONFIG_H },
        ],
        lastModified: new Date().toISOString(),
    }
    writeFileSync(
        join(prefsDir, 'dcc-rail-commander-preferences.json'),
        JSON.stringify({ savedConfigurations: [savedConfig] }, null, 2),
        'utf-8',
    )

    const args = [
        ELECTRON_MAIN,
        '--mock-device',
        '--mock-upload',
        '--skip-startup',
        `--test-data-dir=${testDataDir}`,
        '--disable-gpu',
        '--no-sandbox',
        '--offscreen',
        '--js-flags=--no-expose-wasm',
    ]

    const app = await electron.launch({ args, chromiumSandbox: false, env: ELECTRON_ENV })
    return { app, testDataDir }
}

async function launchRosterGroupedApp(): Promise<{ app: ElectronApplication; testDataDir: string }> {
    const testDataDir = mkdtempSync(join(tmpdir(), 'dcc-rail-commander-e2e-grp-'))

    const scratchPath = join(testDataDir, 'scratch', 'CommandStation-EX')
    mkdirSync(scratchPath, { recursive: true })
    writeFileSync(join(scratchPath, 'myRoster.h'), MOCK_ROSTER_H_GROUPED, 'utf-8')
    writeFileSync(join(scratchPath, 'myTurnouts.h'), MOCK_TURNOUTS_H, 'utf-8')
    writeFileSync(join(scratchPath, 'config.h'), MOCK_CONFIG_H, 'utf-8')
    writeFileSync(join(scratchPath, 'CommandStation-EX.ino'), MOCK_SKETCH_INO, 'utf-8')

    const prefsDir = join(testDataDir, 'app-preferences')
    mkdirSync(prefsDir, { recursive: true })
    const savedConfig = {
        id: 'e2e-grouped-roster',
        name: 'E2E Test Layout',
        deviceName: 'Arduino Mega 2560',
        devicePort: '/dev/ttyACM1',
        deviceFqbn: 'arduino:avr:mega:cpu=atmega2560',
        product: 'ex_commandstation',
        productName: 'EX-CommandStation',
        version: 'v5.4.0-Prod',
        repoPath: join(testDataDir, 'scratch'),
        scratchPath,
        configFiles: [
            { name: 'config.h', content: MOCK_CONFIG_H },
            { name: 'myRoster.h', content: MOCK_ROSTER_H_GROUPED },
            { name: 'myTurnouts.h', content: MOCK_TURNOUTS_H },
        ],
        lastModified: new Date().toISOString(),
    }
    writeFileSync(
        join(prefsDir, 'dcc-rail-commander-preferences.json'),
        JSON.stringify({ savedConfigurations: [savedConfig] }, null, 2),
        'utf-8',
    )

    const args = [
        ELECTRON_MAIN,
        '--mock-device',
        '--mock-upload',
        '--skip-startup',
        `--test-data-dir=${testDataDir}`,
        '--disable-gpu',
        '--no-sandbox',
        '--offscreen',
        '--js-flags=--no-expose-wasm',
    ]

    const app = await electron.launch({ args, chromiumSandbox: false, env: ELECTRON_ENV })
    return { app, testDataDir }
}

async function launchCsb1StackedApp(): Promise<{ app: ElectronApplication; testDataDir: string }> {
    const testDataDir = mkdtempSync(join(tmpdir(), 'dcc-rail-commander-e2e-csb1-'))

    const scratchPath = join(testDataDir, 'scratch', 'CommandStation-EX')
    mkdirSync(scratchPath, { recursive: true })
    writeFileSync(join(scratchPath, 'myRoster.h'), MOCK_ROSTER_H, 'utf-8')
    writeFileSync(join(scratchPath, 'myTurnouts.h'), MOCK_TURNOUTS_H, 'utf-8')
    writeFileSync(join(scratchPath, 'config.h'), MOCK_CONFIG_H_CSB1_BASE, 'utf-8')
    writeFileSync(join(scratchPath, 'myAutomation.h'), MOCK_AUTOMATION_STACKED, 'utf-8')
    writeFileSync(join(scratchPath, 'CommandStation-EX.ino'), MOCK_SKETCH_INO, 'utf-8')

    const prefsDir = join(testDataDir, 'app-preferences')
    mkdirSync(prefsDir, { recursive: true })
    const savedConfig = {
        id: 'e2e-csb1-stacked',
        name: 'E2E Test Layout',
        deviceName: 'EX-CSB1',
        devicePort: '/dev/ttyUSB9',
        deviceFqbn: 'esp32:esp32:esp32',
        product: 'ex_commandstation',
        productName: 'EX-CommandStation',
        version: 'v5.4.0-Prod',
        repoPath: join(testDataDir, 'scratch'),
        scratchPath,
        configFiles: [
            { name: 'config.h', content: MOCK_CONFIG_H_CSB1_BASE },
            { name: 'myAutomation.h', content: MOCK_AUTOMATION_STACKED },
            { name: 'myRoster.h', content: MOCK_ROSTER_H },
            { name: 'myTurnouts.h', content: MOCK_TURNOUTS_H },
        ],
        lastModified: new Date().toISOString(),
    }
    writeFileSync(
        join(prefsDir, 'dcc-rail-commander-preferences.json'),
        JSON.stringify({ savedConfigurations: [savedConfig] }, null, 2),
        'utf-8',
    )

    const args = [
        ELECTRON_MAIN,
        '--mock-device',
        '--mock-upload',
        '--skip-startup',
        `--test-data-dir=${testDataDir}`,
        '--disable-gpu',
        '--no-sandbox',
        '--offscreen',
        '--js-flags=--no-expose-wasm',
    ]

    const app = await electron.launch({ args, chromiumSandbox: false, env: ELECTRON_ENV })
    return { app, testDataDir }
}

// ── Onboarding (home screen, no saved configs) — drives the "New Device" wizard ──

async function launchOnboardingApp(): Promise<{ app: ElectronApplication; testDataDir: string }> {
    const testDataDir = mkdtempSync(join(tmpdir(), 'dcc-rail-commander-e2e-onboarding-'))

    const args = [
        ELECTRON_MAIN,
        '--mock-device',
        '--mock-upload',
        '--skip-startup',
        `--test-data-dir=${testDataDir}`,
        '--disable-gpu',
        '--no-sandbox',
        '--offscreen',
        '--js-flags=--no-expose-wasm',
    ]

    const app = await electron.launch({ args, chromiumSandbox: false, env: ELECTRON_ENV })
    return { app, testDataDir }
}

async function navigateToOnboarding(app: ElectronApplication): Promise<Page> {
    const page = await app.firstWindow()
    page.on('dialog', (dialog) => dialog.accept().catch(() => undefined))
    await page.waitForLoadState('domcontentloaded')
    await page.evaluate(() => {
        document.querySelectorAll('[id^="ej2-licensing"]').forEach(el => el.remove())
    }).catch(() => undefined)
    await expect(page.getByText('New Device', { exact: true })).toBeVisible({ timeout: 15_000 })
    return page
}

// ── Shared test base with workspace fixtures ──────────────────────────────────

async function navigateToIOExpanderWorkspace(app: ElectronApplication): Promise<Page> {
    const page = await app.firstWindow()
    page.on('dialog', (dialog) => dialog.accept().catch(() => undefined))
    await page.waitForLoadState('domcontentloaded')
    await page.evaluate(() => {
        document.querySelectorAll('[id^="ej2-licensing"]').forEach(el => el.remove())
    }).catch(() => undefined)
    await expect(page.getByText('E2E Test Layout')).toBeVisible({ timeout: 15_000 })
    await page.getByText('E2E Test Layout').click()
    // IOExpander has no Roster; wait for the config file tab instead.
    // Use .first() because 'myConfig.h' also appears in the file content area.
    await expect(page.getByText('myConfig.h').first()).toBeVisible({ timeout: 10_000 })
    return page
}

export const test = base.extend<WorkspaceFixtures>({
    // eslint-disable-next-line no-empty-pattern
    electronApp: async ({ }, use) => {
        const { app, testDataDir } = await launchApp()
        await use(app)
        await app.close()
        cleanupDir(testDataDir)
    },

    workspacePage: async ({ electronApp }, use) => {
        await use(await navigateToWorkspace(electronApp))
    },

    // ── CSB1 stacked-shield regression workspace ───────────────────────────
    // eslint-disable-next-line no-empty-pattern
    csb1StackedApp: async ({ }, use) => {
        const { app, testDataDir } = await launchCsb1StackedApp()
        await use(app)
        await app.close()
        cleanupDir(testDataDir)
    },

    csb1StackedPage: async ({ csb1StackedApp }, use) => {
        await use(await navigateToWorkspace(csb1StackedApp))
    },

    // ── IOExpander workspace ──────────────────────────────────────────────────
    // eslint-disable-next-line no-empty-pattern
    ioExpanderApp: async ({ }, use) => {
        const { app, testDataDir } = await launchIOExpanderApp()
        await use(app)
        await app.close()
        cleanupDir(testDataDir)
    },

    ioExpanderPage: async ({ ioExpanderApp }, use) => {
        await use(await navigateToIOExpanderWorkspace(ioExpanderApp))
    },

    // ── Grouped roster workspace ──────────────────────────────────────────────
    // eslint-disable-next-line no-empty-pattern
    rosterGroupedApp: async ({ }, use) => {
        const { app, testDataDir } = await launchRosterGroupedApp()
        await use(app)
        await app.close()
        cleanupDir(testDataDir)
    },

    rosterGroupedPage: async ({ rosterGroupedApp }, use) => {
        await use(await navigateToWorkspace(rosterGroupedApp))
    },

    // ── Onboarding / "New Device" wizard ────────────────────────────────────
    // eslint-disable-next-line no-empty-pattern
    onboardingApp: async ({ }, use) => {
        const { app, testDataDir } = await launchOnboardingApp()
        await use(app)
        await app.close()
        cleanupDir(testDataDir)
    },

    onboardingPage: async ({ onboardingApp }, use) => {
        await use(await navigateToOnboarding(onboardingApp))
    },
})

export { expect }
