/**
 * Single source of truth for the EXRAIL block canvas editor's language surface:
 * palette contents, node color/label, param shape, availability gating, and
 * the EXRAIL text emitted for each block. Extending the language (a new
 * stack/cap command) means adding one entry here.
 */

import type { BlockTypeDef, DefinedObjects } from './exrail-block-compiler'

export type { BlockShape, BlockParamDef, BlockTypeDef, DefinedObjects, CanvasNodeInfo, ParsedGraph, ParseResult } from './exrail-block-compiler'

const hasTurnouts = (d: DefinedObjects) => d.turnouts.length > 0
const hasSensors = (d: DefinedObjects) => (d.sensors ?? []).length > 0
const hasSignals = (d: DefinedObjects) => d.signals.length > 0
const hasRoster = (d: DefinedObjects) => d.roster.length > 0
const hasRouteOrSequence = (d: DefinedObjects) => (d.routes?.length ?? 0) + (d.sequences?.length ?? 0) > 0
const hasTracks = (d: DefinedObjects) => (d.tracks ?? []).length > 0

export const BLOCK_REGISTRY: BlockTypeDef[] = [
    {
        id: 'ROUTE',
        shape: 'hat',
        label: 'Route',
        description: 'Defines starting point of a sequence that will appear as a route on throttle buttons.',
        color: '#2c3e50',
        category: '', // never placed from the toolbox
        params: [],
        isAvailable: () => true,
        emit: () => 'ROUTE',
    },
    {
        id: 'SEQUENCE',
        shape: 'hat',
        label: 'Sequence',
        description: 'Provides a unique label that can be used to call, follow or start.',
        color: '#2c3e50',
        category: '',
        params: [],
        isAvailable: () => true,
        emit: () => 'SEQUENCE',
    },
    {
        id: 'THROW',
        shape: 'stack',
        label: 'Throw turnout',
        description: 'Throws given turnout.',
        color: '#e67e22',
        category: 'Turnouts',
        params: [{ name: 'turnoutId', label: 'Turnout', kind: 'turnoutRef' }],
        isAvailable: hasTurnouts,
        emit: (p) => `THROW(${p.turnoutId})`,
    },
    {
        id: 'CLOSE',
        shape: 'stack',
        label: 'Close turnout',
        description: 'Closes turnout by id.',
        color: '#e67e22',
        category: 'Turnouts',
        params: [{ name: 'turnoutId', label: 'Turnout', kind: 'turnoutRef' }],
        isAvailable: hasTurnouts,
        emit: (p) => `CLOSE(${p.turnoutId})`,
    },
    {
        id: 'TOGGLE_TURNOUT',
        shape: 'stack',
        label: 'Toggle turnout',
        description: 'Toggles given turnout.',
        color: '#e67e22',
        category: 'Turnouts',
        params: [{ name: 'turnoutId', label: 'Turnout', kind: 'turnoutRef' }],
        isAvailable: hasTurnouts,
        emit: (p) => `TOGGLE_TURNOUT(${p.turnoutId})`,
        helpUrl: 'https://dcc-ex.com/mkdocs-test/products/ex-commandstation/exrail/command-list/#toggle_turnoutturnout_id',
    },
    {
        id: 'IFCLOSED',
        shape: 'branch',
        label: 'If turnout closed',
        description: 'Checks if given turnout is in the CLOSED state.',
        color: '#8e44ad',
        category: 'Turnouts',
        params: [{ name: 'turnoutId', label: 'Turnout', kind: 'turnoutRef' }],
        isAvailable: hasTurnouts,
        emit: (p) => `IFCLOSED(${p.turnoutId})`,
    },
    {
        id: 'IFTHROWN',
        shape: 'branch',
        label: 'If turnout thrown',
        description: 'Checks if given turnout is in the THROWN state.',
        color: '#8e44ad',
        category: 'Turnouts',
        params: [{ name: 'turnoutId', label: 'Turnout', kind: 'turnoutRef' }],
        isAvailable: hasTurnouts,
        emit: (p) => `IFTHROWN(${p.turnoutId})`,
    },
    {
        id: 'SETLOCO',
        shape: 'stack',
        label: 'Set active loco',
        description: 'Sets the loco being handled by the current task.',
        color: '#16a085',
        category: 'Locomotives/Driving',
        params: [{ name: 'locoId', label: 'Loco', kind: 'rosterRef' }],
        isAvailable: hasRoster,
        emit: (p) => `SETLOCO(${p.locoId})`,
    },
    {
        id: 'FWD',
        shape: 'stack',
        label: 'Drive forward',
        description: 'Instructs current loco to set DCC speed, forward direction.',
        color: '#16a085',
        category: 'Locomotives/Driving',
        params: [{ name: 'speed', label: 'Speed', kind: 'number' }],
        isAvailable: () => true,
        emit: (p) => `FWD(${p.speed})`,
    },
    {
        id: 'REV',
        shape: 'stack',
        label: 'Drive reverse',
        description: 'Issues DCC speed packet for current loco in reverse.',
        color: '#16a085',
        category: 'Locomotives/Driving',
        params: [{ name: 'speed', label: 'Speed', kind: 'number' }],
        isAvailable: () => true,
        emit: (p) => `REV(${p.speed})`,
    },
    {
        id: 'SPEED',
        shape: 'stack',
        label: 'Set speed',
        description: "Changes current task's loco speed without changing direction.",
        color: '#16a085',
        category: 'Locomotives/Driving',
        params: [{ name: 'speed', label: 'Speed', kind: 'number' }],
        isAvailable: () => true,
        emit: (p) => `SPEED(${p.speed})`,
    },
    {
        id: 'STOP',
        shape: 'stack',
        label: 'Stop',
        description: 'Same as SPEED(0).',
        color: '#16a085',
        category: 'Locomotives/Driving',
        params: [],
        isAvailable: () => true,
        emit: () => 'STOP',
    },
    {
        id: 'ESTOP',
        shape: 'stack',
        label: 'Emergency stop',
        description: 'Performs emergency stop on current task loco.',
        color: '#16a085',
        category: 'Locomotives/Driving',
        params: [],
        isAvailable: () => true,
        emit: () => 'ESTOP',
    },
    {
        id: 'FON',
        shape: 'stack',
        label: 'Function on',
        description: 'Turns on current loco function.',
        color: '#16a085',
        category: 'Locomotives/Functions',
        params: [{ name: 'func', label: 'Function', kind: 'number' }],
        isAvailable: () => true,
        emit: (p) => `FON(${p.func})`,
    },
    {
        id: 'FOFF',
        shape: 'stack',
        label: 'Function off',
        description: 'Turns off current loco function.',
        color: '#16a085',
        category: 'Locomotives/Functions',
        params: [{ name: 'func', label: 'Function', kind: 'number' }],
        isAvailable: () => true,
        emit: (p) => `FOFF(${p.func})`,
    },
    {
        id: 'XFON',
        shape: 'stack',
        label: 'Other loco function on',
        description: 'Turns a function ON for given loco.',
        color: '#16a085',
        category: 'Locomotives/Functions',
        params: [
            { name: 'locoId', label: 'Loco', kind: 'rosterRef' },
            { name: 'func', label: 'Function', kind: 'number' },
        ],
        isAvailable: hasRoster,
        emit: (p) => `XFON(${p.locoId}, ${p.func})`,
    },
    {
        id: 'XFOFF',
        shape: 'stack',
        label: 'Other loco function off',
        description: 'Turns a function OFF for given loco.',
        color: '#16a085',
        category: 'Locomotives/Functions',
        params: [
            { name: 'locoId', label: 'Loco', kind: 'rosterRef' },
            { name: 'func', label: 'Function', kind: 'number' },
        ],
        isAvailable: hasRoster,
        emit: (p) => `XFOFF(${p.locoId}, ${p.func})`,
    },
    {
        id: 'RED',
        shape: 'stack',
        label: 'Signal red',
        description: 'Sets signal to RED state.',
        color: '#c0392b',
        category: 'Signals',
        params: [{ name: 'signalId', label: 'Signal', kind: 'signalRef' }],
        isAvailable: hasSignals,
        emit: (p) => `RED(${p.signalId})`,
    },
    {
        id: 'AMBER',
        shape: 'stack',
        label: 'Signal amber',
        description: 'Sets signal to AMBER state.',
        color: '#c0392b',
        category: 'Signals',
        params: [{ name: 'signalId', label: 'Signal', kind: 'signalRef' }],
        isAvailable: hasSignals,
        emit: (p) => `AMBER(${p.signalId})`,
    },
    {
        id: 'GREEN',
        shape: 'stack',
        label: 'Signal green',
        description: 'Sets signal to GREEN state.',
        color: '#c0392b',
        category: 'Signals',
        params: [{ name: 'signalId', label: 'Signal', kind: 'signalRef' }],
        isAvailable: hasSignals,
        emit: (p) => `GREEN(${p.signalId})`,
    },
    {
        id: 'IF',
        shape: 'branch',
        label: 'If sensor active',
        description: 'Checks sensor state — if false, jumps to the matching ELSE or ENDIF.',
        color: '#8e44ad',
        category: 'Sensors',
        params: [{ name: 'sensorId', label: 'Sensor', kind: 'sensorRef' }],
        isAvailable: hasSensors,
        emit: (p) => `IF(${p.sensorId})`,
    },
    {
        id: 'IFNOT',
        shape: 'branch',
        label: 'If sensor inactive',
        description: 'Inverse of IF.',
        color: '#8e44ad',
        category: 'Sensors',
        params: [{ name: 'sensorId', label: 'Sensor', kind: 'sensorRef' }],
        isAvailable: hasSensors,
        emit: (p) => `IFNOT(${p.sensorId})`,
    },
    {
        id: 'AT',
        shape: 'stack',
        label: 'Wait for sensor active',
        description: 'Wait until a sensor becomes active.',
        color: '#8e44ad',
        category: 'Sensors',
        params: [{ name: 'sensorId', label: 'Sensor', kind: 'sensorRef' }],
        isAvailable: hasSensors,
        emit: (p) => `AT(${p.sensorId})`,
        helpUrl: 'https://dcc-ex.com/mkdocs-test/products/ex-commandstation/exrail/command-list/#atvpin',
    },
    {
        id: 'AFTER',
        shape: 'stack',
        label: 'Wait for sensor pulse',
        description: 'Waits for sensor activated, then deactivated for the given time.',
        color: '#8e44ad',
        category: 'Sensors',
        params: [
            { name: 'sensorId', label: 'Sensor', kind: 'sensorRef' },
            { name: 'timer', label: 'Timeout (ms)', kind: 'number' },
        ],
        isAvailable: hasSensors,
        emit: (p) => `AFTER(${p.sensorId}, ${p.timer})`,
        helpUrl: 'https://dcc-ex.com/mkdocs-test/products/ex-commandstation/exrail/command-list/#aftervpintimer',
    },
    {
        id: 'AFTEROVERLOAD',
        shape: 'stack',
        label: 'Wait for track overload cleared',
        description: 'Waits for overload to be resolved.',
        color: '#7f8c8d',
        category: 'Control',
        params: [{ name: 'trackId', label: 'Track', kind: 'trackRef' }],
        isAvailable: hasTracks,
        emit: (p) => `AFTEROVERLOAD(${p.trackId})`,
        helpUrl: 'https://dcc-ex.com/mkdocs-test/products/ex-commandstation/exrail/command-list/#afteroverloadtrack_id',
    },
    {
        id: 'DELAY',
        shape: 'stack',
        label: 'Delay',
        description: 'Waits for given milliseconds delay (this is not blocking).',
        color: '#7f8c8d',
        category: 'Control',
        params: [{ name: 'ms', label: 'Milliseconds', kind: 'number' }],
        isAvailable: () => true,
        emit: (p) => `DELAY(${p.ms})`,
    },
    {
        id: 'DELAYMINS',
        shape: 'stack',
        label: 'Delay (minutes)',
        description: 'Waits for given minutes delay (this is not blocking).',
        color: '#7f8c8d',
        category: 'Control',
        params: [{ name: 'mins', label: 'Minutes', kind: 'number' }],
        isAvailable: () => true,
        emit: (p) => `DELAYMINS(${p.mins})`,
    },
    {
        id: 'DONE',
        shape: 'cap',
        label: 'Done',
        description: 'Stops task loco (if any) and terminates the current task.',
        color: '#34495e',
        category: 'Control',
        params: [],
        isAvailable: () => true,
        emit: () => 'DONE',
    },
    {
        id: 'FOLLOW',
        shape: 'cap',
        label: 'Follow route/sequence',
        description: 'Task processing follows the given route or sequence (effectively a GoTo).',
        color: '#34495e',
        category: 'Control',
        params: [{ name: 'target', label: 'Route/Sequence', kind: 'routeOrSequenceRef' }],
        isAvailable: hasRouteOrSequence,
        emit: (p) => `FOLLOW(${p.target})`,
    },
]
